services:
  # PostgreSQL Database Service
  db:
    image: postgres:15.13-alpine3.22
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Go Backend Service
  backend:
    container_name: go_backend
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BACKEND_PORT: ${BACKEND_PORT}
    depends_on:
      - db

  # Vuetify Frontend Service
  frontend:
    container_name: vuetify_frontend
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # Mount the src directory for hot-reloading
      - ./frontend/src:/app/src 
    depends_on:
      - backend

volumes:
  postgres_data:
